name: Vue.js CI with Ngrok

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  

    - name: Install dependencies in week7 folder
      run: npm install
      working-directory: ./week7/reusable-portal  

    - name: Run the application in week7 folder
      run: npm run serve &
      working-directory: ./week7/reusable-portal

    - name: Install ngrok
      run: npm install -g ngrok

    - name: Set ngrok authtoken
      run: ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

    - name: Start ngrok and expose the server
      run: ngrok http https://localhost:8080 &

    - name: Display ngrok public URL
      run: curl --silent http://localhost:4040/api/tunnels | jq '.tunnels[0].public_url'

    - name: Wait for 5 minutes
      run: sleep 300  

    - name: Stop the server
      run: killall node
